
DEBUG_MODE = False

API_KEY= "yzczdzxsmw9w9tq9"
API_SECRET = "2k7oo9x1w0xl5g9789wl8j6v4u03lq0x"

ANGEL_API_KEY= "XkcEZ9Gl"
ANGEL_API_SECRET = "94c16823-8f13-429f-813b-ea68dfee8276"
ANGEL_CLIENT_ID = "A51972092"
ANGEL_PASSWORD = "9842"
ANGEL_QR_CODE = "5QCKTA5QKYSL4TDB43RYMGVW3I"

KEY_NIFTYBANK = "NIFTY BANK"
KEY_BANKNIFTY_FUT = "BANKNIFTY"
KEY_NIFTY = "NIFTY 50"
KEY_NIFTY_FUT = "NIFTY"
KEY_FINNIFTY = ""

KEY_CE = "CE"
KEY_PE = "PE"
KEY_FUT = "FUT"
KEY_EQ = "EQ"

KEY_LONG = "long"
KEY_SHORT = "short"

RISK_FREE_INTEREST_RATE = 6.5

MARKET_OPEN_TIME = '09:00:00'
MARKET_CLOSE_TIME = '15:30:00'

BNF_STRIKE_INTERVAL = 100
BNF_OPTION_MAX_QTY = 900

MAXIMUM_STOPLOSS_SPOT = 200

ORDER_PLACED = "orderplaced"
ORDER_ERROR = "ordererror"
ORDER_ERROR_READ_TIMEOUT = "readtimeout"
ORDER_ERROR_0_POSITION_SIZING = "ordererror_0_position_sizing"


NOT_INITIATED = -4
INITIATED = -5
NO_RESPONSE = 0
EXECUTED = 1
PENDING = -1
CANCELLED = -2
REJECTED = -3

AGGRESIVE = "aggresive"
DEFENSIVE = "defensive"
BOUNCE = "bounce"

LONG = "long"
SHORT = "short"

ORDER_PLACED = "orderplaced"
ORDER_ERROR = "ordererror"
ORDER_ERROR_0_POSITION_SIZING = "ordererror_0_position_sizing"
ORDER_ERROR_READ_TIMEOUT = "readtimeout"


EXECUTED = 1
PENDING = -1
CANCELLED = -2
REJECTED = -3
NO_RESPONSE = 0
NOT_INITIATED = -4
INITIATED = -5

STATUS_OPEN = "OPEN"
STATUS_COMPLETE = "COMPLETE"
STATUS_CANCELLED = "CANCELLED"
STATUS_REJECTED = "REJECTED"

BUY = "BUY"
SELL = "SELL"

KEY_CE = "CE"
KEY_PE = "PE"

NOBROKER = "nobroker"
ZERODHA = "zerodha"
ANGELONE = "angelone"
FINVASIA = "finvasia"