# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'options_rifle_UI_2.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QComboBox, QFrame,
    QLabel, QLineEdit, QMainWindow, QPushButton,
    QSizePolicy, QSpinBox, QStatusBar, QTabWidget,
    QWidget)

class Ui_main(object):
    def setupUi(self, main):
        if not main.objectName():
            main.setObjectName(u"main")
        main.resize(357, 469)
        main.setMinimumSize(QSize(357, 469))
        main.setMaximumSize(QSize(357, 942))
        font = QFont()
        font.setFamilies([u"Graphie"])
        main.setFont(font)
        main.setAutoFillBackground(False)
        main.setStyleSheet(u"background:#27292F")
        main.setTabShape(QTabWidget.Rounded)
        self.MainWinodw2 = QWidget(main)
        self.MainWinodw2.setObjectName(u"MainWinodw2")
        self.MainWinodw2.setEnabled(True)
        self.MainWinodw2.setFocusPolicy(Qt.NoFocus)
        self.MainWinodw2.setAutoFillBackground(False)
        self.MainWinodw2.setStyleSheet(u"background: #27292F")
        self.spinner_ticker = QComboBox(self.MainWinodw2)
        self.spinner_ticker.setObjectName(u"spinner_ticker")
        self.spinner_ticker.setGeometry(QRect(30, 27, 161, 31))
        font1 = QFont()
        font1.setFamilies([u"Inter"])
        self.spinner_ticker.setFont(font1)
        self.spinner_ticker.setStyleSheet(u"color:#F3EF52;\n"
"")
        self.spinner_ticker.setMaxVisibleItems(10)
        self.spinner_ticker.setMaxCount(2147483646)
        self.btn_long = QPushButton(self.MainWinodw2)
        self.btn_long.setObjectName(u"btn_long")
        self.btn_long.setGeometry(QRect(250, 27, 31, 31))
        font2 = QFont()
        font2.setFamilies([u"Graphie"])
        font2.setBold(False)
        self.btn_long.setFont(font2)
        self.btn_long.setIconSize(QSize(28, 28))
        self.btn_short = QPushButton(self.MainWinodw2)
        self.btn_short.setObjectName(u"btn_short")
        self.btn_short.setGeometry(QRect(290, 27, 31, 31))
        self.btn_short.setFont(font)
        self.btn_short.setIconSize(QSize(28, 28))
        self.label_riskpertrade = QLabel(self.MainWinodw2)
        self.label_riskpertrade.setObjectName(u"label_riskpertrade")
        self.label_riskpertrade.setGeometry(QRect(30, 380, 80, 16))
        self.label_riskpertrade.setFont(font1)
        self.label_riskpertrade.setStyleSheet(u"color:white")
        self.et_risk = QLineEdit(self.MainWinodw2)
        self.et_risk.setObjectName(u"et_risk")
        self.et_risk.setEnabled(True)
        self.et_risk.setGeometry(QRect(29, 402, 91, 24))
        self.et_risk.setFont(font1)
        self.et_risk.setStyleSheet(u"QLineEdit {\n"
"        background-color: #0000000;\n"
"        border: 1px solid white;\n"
"		color:white;\n"
"		border-radius:5px\n"
"    }")
        self.label_mtm_label = QLabel(self.MainWinodw2)
        self.label_mtm_label.setObjectName(u"label_mtm_label")
        self.label_mtm_label.setGeometry(QRect(280, 742, 41, 21))
        font3 = QFont()
        font3.setFamilies([u"Inter"])
        font3.setPointSize(12)
        self.label_mtm_label.setFont(font3)
        self.label_mtm_label.setStyleSheet(u"color:#9F9F9F")
        self.label_MTM = QLabel(self.MainWinodw2)
        self.label_MTM.setObjectName(u"label_MTM")
        self.label_MTM.setGeometry(QRect(80, 768, 241, 31))
        font4 = QFont()
        font4.setFamilies([u"Inter"])
        font4.setPointSize(24)
        self.label_MTM.setFont(font4)
        self.label_MTM.setStyleSheet(u"color:white")
        self.label_MTM.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.btn_execute = QPushButton(self.MainWinodw2)
        self.btn_execute.setObjectName(u"btn_execute")
        self.btn_execute.setGeometry(QRect(229, 396, 91, 31))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(243, 239, 82, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.btn_execute.setPalette(palette)
        font5 = QFont()
        self.btn_execute.setFont(font5)
        self.btn_execute.setStyleSheet(u"QPushButton  {\n"
"  font-size:12px;\n"
"  width:140px;\n"
"  height:50px;\n"
"  border-width:1px;\n"
"  color:rgba(0, 0, 0, 1);\n"
"  border-color:rgba(24, 171, 41, 0);\n"
"  border-radius:15px;\n"
"  background:rgba(243, 239, 82, 1);\n"
"}\n"
"\n"
"QPushButton :hover {\n"
"  background: rgba(191, 188, 50, 1)!important;\n"
"}")
        self.btn_execute.setAutoDefault(False)
        self.btn_execute.setFlat(False)
        self.line_2 = QFrame(self.MainWinodw2)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(29, 723, 291, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.label_label_spot = QLabel(self.MainWinodw2)
        self.label_label_spot.setObjectName(u"label_label_spot")
        self.label_label_spot.setGeometry(QRect(30, 68, 47, 13))
        self.label_label_spot.setFont(font1)
        self.label_label_spot.setStyleSheet(u"color:#9F9F9F")
        self.label_spot = QLabel(self.MainWinodw2)
        self.label_spot.setObjectName(u"label_spot")
        self.label_spot.setGeometry(QRect(30, 88, 81, 16))
        font6 = QFont()
        font6.setFamilies([u"Inter"])
        font6.setPointSize(11)
        font6.setBold(False)
        self.label_spot.setFont(font6)
        self.label_spot.setStyleSheet(u"color:white")
        self.label_label_call_strike = QLabel(self.MainWinodw2)
        self.label_label_call_strike.setObjectName(u"label_label_call_strike")
        self.label_label_call_strike.setGeometry(QRect(99, 128, 61, 13))
        self.label_label_call_strike.setFont(font1)
        self.label_label_call_strike.setStyleSheet(u"color:#9F9F9F")
        self.label_label_call_h_strike = QLabel(self.MainWinodw2)
        self.label_label_call_h_strike.setObjectName(u"label_label_call_h_strike")
        self.label_label_call_h_strike.setGeometry(QRect(196, 128, 74, 16))
        self.label_label_call_h_strike.setFont(font1)
        self.label_label_call_h_strike.setCursor(QCursor(Qt.ArrowCursor))
        self.label_label_call_h_strike.setFocusPolicy(Qt.NoFocus)
        self.label_label_call_h_strike.setStyleSheet(u"color:#9F9F9F")
        self.line_3 = QFrame(self.MainWinodw2)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(30, 470, 291, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.spin_stoploss = QSpinBox(self.MainWinodw2)
        self.spin_stoploss.setObjectName(u"spin_stoploss")
        self.spin_stoploss.setGeometry(QRect(127, 250, 105, 24))
        palette1 = QPalette()
        brush2 = QBrush(QColor(255, 255, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        brush3 = QBrush(QColor(39, 41, 47, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Highlight, brush1)
        palette1.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Link, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Link, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        brush4 = QBrush(QColor(0, 120, 215, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Disabled, QPalette.Highlight, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Link, brush1)
        self.spin_stoploss.setPalette(palette1)
        font7 = QFont()
        font7.setFamilies([u"Inter"])
        font7.setPointSize(10)
        self.spin_stoploss.setFont(font7)
        self.spin_stoploss.setStyleSheet(u"color:white;")
        self.spin_stoploss.setAlignment(Qt.AlignCenter)
        self.spin_stoploss.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_stoploss.setMaximum(1000000)
        self.spin_stoploss.setSingleStep(1)
        self.label_stoploss = QLabel(self.MainWinodw2)
        self.label_stoploss.setObjectName(u"label_stoploss")
        self.label_stoploss.setGeometry(QRect(150, 280, 59, 16))
        self.label_stoploss.setFont(font1)
        self.label_stoploss.setStyleSheet(u"color:white")
        self.label_stoploss.setAlignment(Qt.AlignCenter)
        self.btn_editrisk = QPushButton(self.MainWinodw2)
        self.btn_editrisk.setObjectName(u"btn_editrisk")
        self.btn_editrisk.setGeometry(QRect(128, 403, 21, 21))
        self.btn_editrisk.setFont(font2)
        self.btn_editrisk.setStyleSheet(u"background:#00000000")
        icon = QIcon()
        icon.addFile(u"C:/Users/Admin/icons/btn_edit_risk.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_editrisk.setIcon(icon)
        self.btn_editrisk.setIconSize(QSize(20, 20))
        self.frame_trade = QFrame(self.MainWinodw2)
        self.frame_trade.setObjectName(u"frame_trade")
        self.frame_trade.setGeometry(QRect(30, 494, 291, 228))
        self.frame_trade.setFrameShape(QFrame.NoFrame)
        self.frame_trade.setFrameShadow(QFrame.Plain)
        self.icon_trade_type = QPushButton(self.frame_trade)
        self.icon_trade_type.setObjectName(u"icon_trade_type")
        self.icon_trade_type.setGeometry(QRect(4, 5, 31, 31))
        self.icon_trade_type.setStyleSheet(u"background:rgba(0, 0, 0, 0);")
        icon1 = QIcon()
        icon1.addFile(u"C:/Users/Admin/icons/icon_arrow_long.png", QSize(), QIcon.Normal, QIcon.Off)
        self.icon_trade_type.setIcon(icon1)
        self.icon_trade_type.setIconSize(QSize(26, 26))
        self.label_instrument = QLabel(self.frame_trade)
        self.label_instrument.setObjectName(u"label_instrument")
        self.label_instrument.setGeometry(QRect(105, 11, 177, 16))
        font8 = QFont()
        font8.setFamilies([u"Inter"])
        font8.setPointSize(14)
        font8.setBold(True)
        self.label_instrument.setFont(font8)
        self.label_instrument.setStyleSheet(u"color:white")
        self.label_instrument.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.border_label = QLabel(self.frame_trade)
        self.border_label.setObjectName(u"border_label")
        self.border_label.setGeometry(QRect(0, 0, 291, 228))
        self.border_label.setStyleSheet(u"border-radius: 9px; \n"
"border:1px solid #FFFFFF;")
        self.label_label_qty = QLabel(self.frame_trade)
        self.label_label_qty.setObjectName(u"label_label_qty")
        self.label_label_qty.setGeometry(QRect(53, 46, 21, 16))
        self.label_label_qty.setFont(font1)
        self.label_label_qty.setStyleSheet(u"color:#9F9F9F")
        self.label_label_avg = QLabel(self.frame_trade)
        self.label_label_avg.setObjectName(u"label_label_avg")
        self.label_label_avg.setGeometry(QRect(134, 46, 21, 16))
        self.label_label_avg.setFont(font1)
        self.label_label_avg.setStyleSheet(u"color:#9F9F9F")
        self.label_3 = QLabel(self.frame_trade)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(216, 46, 21, 16))
        self.label_3.setFont(font1)
        self.label_3.setStyleSheet(u"color:#9F9F9F")
        self.label_trade_qty = QLabel(self.frame_trade)
        self.label_trade_qty.setObjectName(u"label_trade_qty")
        self.label_trade_qty.setGeometry(QRect(31, 66, 61, 16))
        self.label_trade_qty.setFont(font6)
        self.label_trade_qty.setStyleSheet(u"color:white")
        self.label_trade_qty.setAlignment(Qt.AlignCenter)
        self.label_avg_price = QLabel(self.frame_trade)
        self.label_avg_price.setObjectName(u"label_avg_price")
        self.label_avg_price.setGeometry(QRect(114, 66, 61, 16))
        self.label_avg_price.setFont(font6)
        self.label_avg_price.setStyleSheet(u"color:white")
        self.label_avg_price.setAlignment(Qt.AlignCenter)
        self.label_trade_ltp = QLabel(self.frame_trade)
        self.label_trade_ltp.setObjectName(u"label_trade_ltp")
        self.label_trade_ltp.setGeometry(QRect(196, 66, 61, 16))
        self.label_trade_ltp.setFont(font6)
        self.label_trade_ltp.setStyleSheet(u"color:white")
        self.label_trade_ltp.setAlignment(Qt.AlignCenter)
        self.label_strategy = QLabel(self.frame_trade)
        self.label_strategy.setObjectName(u"label_strategy")
        self.label_strategy.setGeometry(QRect(31, 4, 31, 31))
        font9 = QFont()
        font9.setFamilies([u"Inter"])
        font9.setPointSize(9)
        font9.setBold(True)
        self.label_strategy.setFont(font9)
        self.label_strategy.setStyleSheet(u"background:rgba(0, 0, 0, 0);color:white")
        self.label_strategy.setAlignment(Qt.AlignCenter)
        self.label = QLabel(self.frame_trade)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(140, 94, 16, 21))
        font10 = QFont()
        font10.setFamilies([u"Inter"])
        font10.setPointSize(10)
        font10.setBold(False)
        self.label.setFont(font10)
        self.label.setStyleSheet(u"color:#9F9F9F")
        self.label_profit = QLabel(self.frame_trade)
        self.label_profit.setObjectName(u"label_profit")
        self.label_profit.setGeometry(QRect(148, 202, 131, 20))
        self.label_profit.setFont(font7)
        self.label_profit.setStyleSheet(u"color:white")
        self.label_profit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_risk = QLabel(self.frame_trade)
        self.label_risk.setObjectName(u"label_risk")
        self.label_risk.setGeometry(QRect(9, 202, 131, 20))
        self.label_risk.setFont(font7)
        self.label_risk.setStyleSheet(u"color:white")
        self.label_risk.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_label_risk = QLabel(self.frame_trade)
        self.label_label_risk.setObjectName(u"label_label_risk")
        self.label_label_risk.setGeometry(QRect(10, 164, 47, 13))
        self.label_label_risk.setFont(font1)
        self.label_label_risk.setStyleSheet(u"color:#9F9F9F")
        self.label_label_profit = QLabel(self.frame_trade)
        self.label_label_profit.setObjectName(u"label_label_profit")
        self.label_label_profit.setGeometry(QRect(229, 164, 47, 13))
        self.label_label_profit.setFont(font1)
        self.label_label_profit.setStyleSheet(u"color:#9F9F9F")
        self.label_label_profit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.frame = QFrame(self.frame_trade)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(68, 120, 162, 32))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.border_label_2 = QLabel(self.frame)
        self.border_label_2.setObjectName(u"border_label_2")
        self.border_label_2.setGeometry(QRect(0, 0, 162, 32))
        self.border_label_2.setStyleSheet(u"border-radius: 9px; \n"
"border:1px solid #FFFFFF;")
        self.et_stoploss = QLineEdit(self.frame)
        self.et_stoploss.setObjectName(u"et_stoploss")
        self.et_stoploss.setGeometry(QRect(49, 2, 61, 27))
        font11 = QFont()
        font11.setFamilies([u"Inter"])
        font11.setPointSize(11)
        self.et_stoploss.setFont(font11)
        self.et_stoploss.setStyleSheet(u"QLineEdit {\n"
"        background-color: #0000000;\n"
"        border: 1px solid #0000000;\n"
"		color:white;\n"
"		border-radius:5px;\n"
"    }")
        self.et_stoploss.setAlignment(Qt.AlignCenter)
        self.btn_increase_sl = QPushButton(self.frame)
        self.btn_increase_sl.setObjectName(u"btn_increase_sl")
        self.btn_increase_sl.setGeometry(QRect(111, 2, 21, 29))
        self.btn_increase_sl.setStyleSheet(u"background:rgba(0, 0, 0, 0);")
        icon2 = QIcon()
        icon2.addFile(u"C:/Users/Admin/icons/btn_plus.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_increase_sl.setIcon(icon2)
        self.btn_increase_sl.setIconSize(QSize(18, 18))
        self.btn_decrease_sl = QPushButton(self.frame)
        self.btn_decrease_sl.setObjectName(u"btn_decrease_sl")
        self.btn_decrease_sl.setGeometry(QRect(26, 2, 21, 30))
        self.btn_decrease_sl.setStyleSheet(u"background:rgba(0, 0, 0, 0);")
        icon3 = QIcon()
        icon3.addFile(u"C:/Users/Admin/icons/btn_minus.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_decrease_sl.setIcon(icon3)
        self.btn_decrease_sl.setIconSize(QSize(18, 18))
        self.btn_edit_sl = QPushButton(self.frame)
        self.btn_edit_sl.setObjectName(u"btn_edit_sl")
        self.btn_edit_sl.setGeometry(QRect(136, 2, 21, 30))
        self.btn_edit_sl.setStyleSheet(u"background:rgba(0, 0, 0, 0);")
        icon4 = QIcon()
        icon4.addFile(u"C:/Users/Admin/icons/btn_edit_sl.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_edit_sl.setIcon(icon4)
        self.btn_edit_sl.setIconSize(QSize(20, 20))
        self.btn_auto_trail = QPushButton(self.frame)
        self.btn_auto_trail.setObjectName(u"btn_auto_trail")
        self.btn_auto_trail.setGeometry(QRect(4, 2, 21, 29))
        self.btn_auto_trail.setStyleSheet(u"background:rgba(0, 0, 0, 0);")
        self.btn_auto_trail.setIcon(icon2)
        self.btn_auto_trail.setIconSize(QSize(18, 18))
        self.border_label_2.raise_()
        self.btn_increase_sl.raise_()
        self.btn_decrease_sl.raise_()
        self.btn_edit_sl.raise_()
        self.et_stoploss.raise_()
        self.btn_auto_trail.raise_()
        self.label_risk_points = QLabel(self.frame_trade)
        self.label_risk_points.setObjectName(u"label_risk_points")
        self.label_risk_points.setGeometry(QRect(9, 181, 131, 20))
        self.label_risk_points.setFont(font7)
        self.label_risk_points.setStyleSheet(u"color:white")
        self.label_risk_points.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_profit_points = QLabel(self.frame_trade)
        self.label_profit_points.setObjectName(u"label_profit_points")
        self.label_profit_points.setGeometry(QRect(148, 181, 131, 20))
        self.label_profit_points.setFont(font7)
        self.label_profit_points.setStyleSheet(u"color:white")
        self.label_profit_points.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.border_label.raise_()
        self.icon_trade_type.raise_()
        self.label_instrument.raise_()
        self.label_label_qty.raise_()
        self.label_label_avg.raise_()
        self.label_3.raise_()
        self.label_trade_qty.raise_()
        self.label_avg_price.raise_()
        self.label_trade_ltp.raise_()
        self.label_strategy.raise_()
        self.label.raise_()
        self.label_profit.raise_()
        self.label_risk.raise_()
        self.label_label_risk.raise_()
        self.label_label_profit.raise_()
        self.frame.raise_()
        self.label_risk_points.raise_()
        self.label_profit_points.raise_()
        self.label_no_position = QLabel(self.MainWinodw2)
        self.label_no_position.setObjectName(u"label_no_position")
        self.label_no_position.setGeometry(QRect(104, 602, 154, 15))
        self.label_no_position.setFont(font1)
        self.label_no_position.setStyleSheet(u"color:#6B6B6B;")
        self.label_no_position.setAlignment(Qt.AlignCenter)
        self.btn_exit = QPushButton(self.MainWinodw2)
        self.btn_exit.setObjectName(u"btn_exit")
        self.btn_exit.setGeometry(QRect(230, 827, 91, 31))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.btn_exit.setPalette(palette2)
        self.btn_exit.setFont(font5)
        self.btn_exit.setStyleSheet(u"QPushButton  {\n"
"  font-size:12px;\n"
"  width:140px;\n"
"  height:50px;\n"
"  border-width:1px;\n"
"  color:rgba(0, 0, 0, 1);\n"
"  border-color:rgba(24, 171, 41, 0);\n"
"  border-radius:15px;\n"
"  background:rgba(243, 239, 82, 1);\n"
"}\n"
"\n"
"QPushButton :hover {\n"
"  background: rgba(191, 188, 50, 1)!important;\n"
"}")
        self.btn_exit.setAutoDefault(False)
        self.btn_exit.setFlat(False)
        self.line_4 = QFrame(self.MainWinodw2)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(29, 867, 291, 16))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.btn_auto_t = QPushButton(self.MainWinodw2)
        self.btn_auto_t.setObjectName(u"btn_auto_t")
        self.btn_auto_t.setGeometry(QRect(164, 887, 31, 31))
        self.btn_auto_t.setFont(font2)
        self.btn_auto_t.setStyleSheet(u"color: #000000;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"")
        icon5 = QIcon()
        icon5.addFile(u"../icons/btn_auto_trail_on.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_auto_t.setIcon(icon5)
        self.btn_auto_t.setIconSize(QSize(28, 28))
        self.label_label_call_delta = QLabel(self.MainWinodw2)
        self.label_label_call_delta.setObjectName(u"label_label_call_delta")
        self.label_label_call_delta.setGeometry(QRect(99, 180, 61, 13))
        self.label_label_call_delta.setFont(font1)
        self.label_label_call_delta.setStyleSheet(u"color:#9F9F9F")
        self.label_label_call_h_delta = QLabel(self.MainWinodw2)
        self.label_label_call_h_delta.setObjectName(u"label_label_call_h_delta")
        self.label_label_call_h_delta.setGeometry(QRect(196, 180, 68, 13))
        self.label_label_call_h_delta.setFont(font1)
        self.label_label_call_h_delta.setStyleSheet(u"color:#9F9F9F")
        self.label_futures = QLabel(self.MainWinodw2)
        self.label_futures.setObjectName(u"label_futures")
        self.label_futures.setGeometry(QRect(238, 88, 81, 16))
        self.label_futures.setFont(font6)
        self.label_futures.setStyleSheet(u"color:white")
        self.label_futures.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_label_futures = QLabel(self.MainWinodw2)
        self.label_label_futures.setObjectName(u"label_label_futures")
        self.label_label_futures.setGeometry(QRect(272, 68, 47, 13))
        self.label_label_futures.setFont(font1)
        self.label_label_futures.setStyleSheet(u"color:#9F9F9F")
        self.label_label_futures.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.spin_strike_delta = QSpinBox(self.MainWinodw2)
        self.spin_strike_delta.setObjectName(u"spin_strike_delta")
        self.spin_strike_delta.setGeometry(QRect(98, 198, 75, 20))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette3.setBrush(QPalette.Active, QPalette.Highlight, brush1)
        palette3.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Link, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Link, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Highlight, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Link, brush1)
        self.spin_strike_delta.setPalette(palette3)
        self.spin_strike_delta.setFont(font7)
        self.spin_strike_delta.setStyleSheet(u"color:white;")
        self.spin_strike_delta.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.spin_strike_delta.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_strike_delta.setMaximum(1000000)
        self.spin_hedge_strike_delta = QSpinBox(self.MainWinodw2)
        self.spin_hedge_strike_delta.setObjectName(u"spin_hedge_strike_delta")
        self.spin_hedge_strike_delta.setGeometry(QRect(190, 198, 75, 20))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette4.setBrush(QPalette.Active, QPalette.Highlight, brush1)
        palette4.setBrush(QPalette.Active, QPalette.HighlightedText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Link, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette4.setBrush(QPalette.Inactive, QPalette.Highlight, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Link, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.Highlight, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.Link, brush1)
        self.spin_hedge_strike_delta.setPalette(palette4)
        self.spin_hedge_strike_delta.setFont(font7)
        self.spin_hedge_strike_delta.setStyleSheet(u"color:white;")
        self.spin_hedge_strike_delta.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.spin_hedge_strike_delta.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.spin_hedge_strike_delta.setMaximum(1000000)
        self.label_position_size = QLabel(self.MainWinodw2)
        self.label_position_size.setObjectName(u"label_position_size")
        self.label_position_size.setGeometry(QRect(77, 316, 202, 44))
        self.label_position_size.setFont(font10)
        self.label_position_size.setStyleSheet(u"color:white")
        self.label_position_size.setScaledContents(False)
        self.label_position_size.setAlignment(Qt.AlignCenter)
        self.cb_strike = QComboBox(self.MainWinodw2)
        self.cb_strike.setObjectName(u"cb_strike")
        self.cb_strike.setGeometry(QRect(98, 150, 75, 22))
        self.cb_strike.setStyleSheet(u"color:#F3EF52;\n"
"")
        self.cb_strike_hedge = QComboBox(self.MainWinodw2)
        self.cb_strike_hedge.setObjectName(u"cb_strike_hedge")
        self.cb_strike_hedge.setGeometry(QRect(190, 150, 75, 22))
        self.cb_strike_hedge.setStyleSheet(u"color:#F3EF52;\n"
"")
        main.setCentralWidget(self.MainWinodw2)
        self.btn_exit.raise_()
        self.btn_long.raise_()
        self.spinner_ticker.raise_()
        self.btn_short.raise_()
        self.label_riskpertrade.raise_()
        self.et_risk.raise_()
        self.label_mtm_label.raise_()
        self.label_MTM.raise_()
        self.btn_execute.raise_()
        self.line_2.raise_()
        self.label_label_spot.raise_()
        self.label_spot.raise_()
        self.label_label_call_strike.raise_()
        self.label_label_call_h_strike.raise_()
        self.line_3.raise_()
        self.spin_stoploss.raise_()
        self.label_stoploss.raise_()
        self.btn_editrisk.raise_()
        self.frame_trade.raise_()
        self.label_no_position.raise_()
        self.line_4.raise_()
        self.btn_auto_t.raise_()
        self.label_label_call_delta.raise_()
        self.label_label_call_h_delta.raise_()
        self.label_futures.raise_()
        self.label_label_futures.raise_()
        self.spin_strike_delta.raise_()
        self.spin_hedge_strike_delta.raise_()
        self.label_position_size.raise_()
        self.cb_strike.raise_()
        self.cb_strike_hedge.raise_()
        self.statusbar = QStatusBar(main)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setStyleSheet(u"color:#F3EF52;")
        main.setStatusBar(self.statusbar)

        self.retranslateUi(main)

        self.btn_execute.setDefault(False)
        self.btn_exit.setDefault(False)


        QMetaObject.connectSlotsByName(main)
    # setupUi

    def retranslateUi(self, main):
        main.setWindowTitle(QCoreApplication.translate("main", u"Options Rifle", None))
        self.btn_long.setText("")
        self.btn_short.setText("")
        self.label_riskpertrade.setText(QCoreApplication.translate("main", u"Risk Per Trade", None))
        self.label_mtm_label.setText(QCoreApplication.translate("main", u"MTM", None))
        self.label_MTM.setText(QCoreApplication.translate("main", u"0.0", None))
        self.btn_execute.setText(QCoreApplication.translate("main", u"Execute", None))
        self.label_label_spot.setText(QCoreApplication.translate("main", u"Spot", None))
        self.label_spot.setText(QCoreApplication.translate("main", u"0.0", None))
        self.label_label_call_strike.setText(QCoreApplication.translate("main", u"Call Strike", None))
        self.label_label_call_h_strike.setText(QCoreApplication.translate("main", u"Call-H Strike", None))
        self.label_stoploss.setText(QCoreApplication.translate("main", u"SL Points", None))
        self.btn_editrisk.setText("")
        self.icon_trade_type.setText("")
        self.label_instrument.setText(QCoreApplication.translate("main", u"45000 CE", None))
        self.border_label.setText("")
        self.label_label_qty.setText(QCoreApplication.translate("main", u"Qty", None))
        self.label_label_avg.setText(QCoreApplication.translate("main", u"Avg.", None))
        self.label_3.setText(QCoreApplication.translate("main", u"LTP", None))
        self.label_trade_qty.setText(QCoreApplication.translate("main", u"0", None))
        self.label_avg_price.setText(QCoreApplication.translate("main", u"0.0", None))
        self.label_trade_ltp.setText(QCoreApplication.translate("main", u"0.0", None))
        self.label_strategy.setText(QCoreApplication.translate("main", u"AT", None))
        self.label.setText(QCoreApplication.translate("main", u"SL", None))
        self.label_profit.setText(QCoreApplication.translate("main", u"+10,900", None))
        self.label_risk.setText(QCoreApplication.translate("main", u"10,900", None))
        self.label_label_risk.setText(QCoreApplication.translate("main", u"Risk", None))
        self.label_label_profit.setText(QCoreApplication.translate("main", u"Profit", None))
        self.border_label_2.setText("")
        self.et_stoploss.setText(QCoreApplication.translate("main", u"223", None))
        self.btn_increase_sl.setText("")
        self.btn_decrease_sl.setText("")
        self.btn_edit_sl.setText("")
        self.btn_auto_trail.setText("")
        self.label_risk_points.setText(QCoreApplication.translate("main", u"-20 | -4", None))
        self.label_profit_points.setText(QCoreApplication.translate("main", u"7 | 12 (60%)", None))
        self.label_no_position.setText(QCoreApplication.translate("main", u"You dont have any position", None))
        self.btn_exit.setText(QCoreApplication.translate("main", u"Exit", None))
        self.btn_auto_t.setText("")
        self.label_label_call_delta.setText(QCoreApplication.translate("main", u"Call Delta", None))
        self.label_label_call_h_delta.setText(QCoreApplication.translate("main", u"Call-H Delta", None))
        self.label_futures.setText(QCoreApplication.translate("main", u"0.0", None))
        self.label_label_futures.setText(QCoreApplication.translate("main", u"Futures", None))
        self.label_position_size.setText(QCoreApplication.translate("main", u"0", None))
    # retranslateUi

