# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'options_rifle_UI_2.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QLabel,
    QLineEdit, QListView, QMainWindow, QPushButton,
    QSizePolicy, QSpinBox, QStatusBar, QTabWidget,
    QWidget)

class Ui_main(object):
    def setupUi(self, main):
        if not main.objectName():
            main.setObjectName(u"main")
        main.resize(357, 899)
        main.setMinimumSize(QSize(357, 899))
        main.setMaximumSize(QSize(357, 899))
        main.setAutoFillBackground(False)
        main.setStyleSheet(u"background:#27292F")
        main.setTabShape(QTabWidget.Rounded)
        self.MainWinodw2 = QWidget(main)
        self.MainWinodw2.setObjectName(u"MainWinodw2")
        self.MainWinodw2.setEnabled(True)
        self.MainWinodw2.setFocusPolicy(Qt.NoFocus)
        self.MainWinodw2.setAutoFillBackground(False)
        self.MainWinodw2.setStyleSheet(u"background: #27292F")
        self.btn_aggresive = QPushButton(self.MainWinodw2)
        self.btn_aggresive.setObjectName(u"btn_aggresive")
        self.btn_aggresive.setEnabled(True)
        self.btn_aggresive.setGeometry(QRect(30, 20, 91, 31))
        palette = QPalette()
        brush = QBrush(QColor(39, 41, 47, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.btn_aggresive.setPalette(palette)
        font = QFont()
        font.setFamilies([u"Graphie"])
        font.setBold(False)
        self.btn_aggresive.setFont(font)
        self.btn_aggresive.setAutoFillBackground(False)
        self.btn_aggresive.setStyleSheet(u"")
        self.btn_aggresive.setAutoDefault(False)
        self.btn_aggresive.setFlat(False)
        self.btn_defensive = QPushButton(self.MainWinodw2)
        self.btn_defensive.setObjectName(u"btn_defensive")
        self.btn_defensive.setGeometry(QRect(130, 20, 91, 31))
        font1 = QFont()
        font1.setFamilies([u"Graphie"])
        self.btn_defensive.setFont(font1)
        self.btn_defensive.setAutoDefault(False)
        self.btn_defensive.setFlat(False)
        self.btn_bounce = QPushButton(self.MainWinodw2)
        self.btn_bounce.setObjectName(u"btn_bounce")
        self.btn_bounce.setEnabled(True)
        self.btn_bounce.setGeometry(QRect(230, 20, 91, 31))
        self.btn_bounce.setFont(font1)
        self.btn_bounce.setAutoDefault(False)
        self.btn_bounce.setFlat(False)
        self.spinner_ticker = QComboBox(self.MainWinodw2)
        self.spinner_ticker.setObjectName(u"spinner_ticker")
        self.spinner_ticker.setGeometry(QRect(30, 80, 161, 31))
        self.spinner_ticker.setFont(font1)
        self.spinner_ticker.setStyleSheet(u"color:#F3EF52;\n"
"")
        self.spinner_ticker.setMaxVisibleItems(10)
        self.spinner_ticker.setMaxCount(2147483646)
        self.btn_long = QPushButton(self.MainWinodw2)
        self.btn_long.setObjectName(u"btn_long")
        self.btn_long.setGeometry(QRect(250, 80, 31, 31))
        self.btn_long.setFont(font)
        self.btn_long.setIconSize(QSize(28, 28))
        self.btn_short = QPushButton(self.MainWinodw2)
        self.btn_short.setObjectName(u"btn_short")
        self.btn_short.setGeometry(QRect(290, 80, 31, 31))
        self.btn_short.setFont(font1)
        self.btn_short.setIconSize(QSize(28, 28))
        self.line = QFrame(self.MainWinodw2)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(30, 60, 291, 16))
        self.line.setStyleSheet(u"color:#3B3D44")
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_riskpertrade = QLabel(self.MainWinodw2)
        self.label_riskpertrade.setObjectName(u"label_riskpertrade")
        self.label_riskpertrade.setGeometry(QRect(30, 810, 80, 16))
        self.label_riskpertrade.setFont(font1)
        self.label_riskpertrade.setStyleSheet(u"color:white")
        self.et_risk = QLineEdit(self.MainWinodw2)
        self.et_risk.setObjectName(u"et_risk")
        self.et_risk.setEnabled(True)
        self.et_risk.setGeometry(QRect(30, 830, 91, 21))
        self.et_risk.setFont(font1)
        self.et_risk.setStyleSheet(u"color:white;\n"
"border-color:black;")
        self.label_mtm_label = QLabel(self.MainWinodw2)
        self.label_mtm_label.setObjectName(u"label_mtm_label")
        self.label_mtm_label.setGeometry(QRect(280, 740, 41, 21))
        font2 = QFont()
        font2.setFamilies([u"Graphie"])
        font2.setPointSize(12)
        self.label_mtm_label.setFont(font2)
        self.label_mtm_label.setStyleSheet(u"color:#9F9F9F")
        self.label_MTM = QLabel(self.MainWinodw2)
        self.label_MTM.setObjectName(u"label_MTM")
        self.label_MTM.setGeometry(QRect(80, 760, 241, 31))
        font3 = QFont()
        font3.setFamilies([u"Graphie"])
        font3.setPointSize(24)
        self.label_MTM.setFont(font3)
        self.label_MTM.setStyleSheet(u"color:white")
        self.label_MTM.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.btn_execute = QPushButton(self.MainWinodw2)
        self.btn_execute.setObjectName(u"btn_execute")
        self.btn_execute.setGeometry(QRect(230, 820, 91, 31))
        palette1 = QPalette()
        brush1 = QBrush(QColor(0, 0, 0, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        brush2 = QBrush(QColor(243, 239, 82, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush1)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.btn_execute.setPalette(palette1)
        self.btn_execute.setFont(font)
        self.btn_execute.setStyleSheet(u"color: #000000;\n"
" background: #F3EF52")
        self.btn_execute.setAutoDefault(False)
        self.btn_execute.setFlat(False)
        self.line_2 = QFrame(self.MainWinodw2)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(30, 720, 291, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.label_label_spot = QLabel(self.MainWinodw2)
        self.label_label_spot.setObjectName(u"label_label_spot")
        self.label_label_spot.setGeometry(QRect(30, 130, 47, 13))
        self.label_label_spot.setFont(font1)
        self.label_label_spot.setStyleSheet(u"color:#9F9F9F")
        self.label_spot = QLabel(self.MainWinodw2)
        self.label_spot.setObjectName(u"label_spot")
        self.label_spot.setGeometry(QRect(30, 150, 81, 16))
        self.label_spot.setFont(font2)
        self.label_spot.setStyleSheet(u"color:white")
        self.label_futures = QLabel(self.MainWinodw2)
        self.label_futures.setObjectName(u"label_futures")
        self.label_futures.setGeometry(QRect(150, 150, 81, 16))
        self.label_futures.setFont(font2)
        self.label_futures.setStyleSheet(u"color:white")
        self.label_label_futures = QLabel(self.MainWinodw2)
        self.label_label_futures.setObjectName(u"label_label_futures")
        self.label_label_futures.setGeometry(QRect(150, 130, 47, 13))
        self.label_label_futures.setFont(font1)
        self.label_label_futures.setStyleSheet(u"color:#9F9F9F")
        self.label_future_diff = QLabel(self.MainWinodw2)
        self.label_future_diff.setObjectName(u"label_future_diff")
        self.label_future_diff.setGeometry(QRect(250, 150, 71, 20))
        self.label_future_diff.setFont(font2)
        self.label_future_diff.setStyleSheet(u"color:white")
        self.label_label_futures_diff = QLabel(self.MainWinodw2)
        self.label_label_futures_diff.setObjectName(u"label_label_futures_diff")
        self.label_label_futures_diff.setGeometry(QRect(250, 130, 71, 16))
        self.label_label_futures_diff.setFont(font1)
        self.label_label_futures_diff.setStyleSheet(u"color:#9F9F9F")
        self.line_3 = QFrame(self.MainWinodw2)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(30, 330, 291, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.spin_stoploss = QSpinBox(self.MainWinodw2)
        self.spin_stoploss.setObjectName(u"spin_stoploss")
        self.spin_stoploss.setGeometry(QRect(110, 210, 131, 31))
        palette2 = QPalette()
        brush3 = QBrush(QColor(255, 255, 255, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush3)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush)
        palette2.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        palette2.setBrush(QPalette.Active, QPalette.HighlightedText, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Link, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Highlight, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Link, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush)
        brush4 = QBrush(QColor(0, 120, 215, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Disabled, QPalette.Highlight, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Link, brush2)
        self.spin_stoploss.setPalette(palette2)
        self.spin_stoploss.setFont(font2)
        self.spin_stoploss.setStyleSheet(u"color:white;")
        self.spin_stoploss.setMaximum(1000000)
        self.label_stoploss = QLabel(self.MainWinodw2)
        self.label_stoploss.setObjectName(u"label_stoploss")
        self.label_stoploss.setGeometry(QRect(150, 250, 47, 13))
        self.label_stoploss.setFont(font1)
        self.label_stoploss.setStyleSheet(u"color:white")
        self.lv_trades = QListView(self.MainWinodw2)
        self.lv_trades.setObjectName(u"lv_trades")
        self.lv_trades.setGeometry(QRect(30, 350, 291, 371))
        self.label_trades = QLabel(self.MainWinodw2)
        self.label_trades.setObjectName(u"label_trades")
        self.label_trades.setGeometry(QRect(150, 310, 61, 16))
        self.label_trades.setFont(font2)
        self.label_trades.setStyleSheet(u"color:white")
        self.btn_editrisk = QPushButton(self.MainWinodw2)
        self.btn_editrisk.setObjectName(u"btn_editrisk")
        self.btn_editrisk.setGeometry(QRect(130, 830, 21, 21))
        self.btn_editrisk.setFont(font)
        self.btn_editrisk.setIconSize(QSize(16, 16))
        self.btn_trans_label_Fut = QPushButton(self.MainWinodw2)
        self.btn_trans_label_Fut.setObjectName(u"btn_trans_label_Fut")
        self.btn_trans_label_Fut.setGeometry(QRect(150, 150, 75, 23))
        self.btn_trans_label_Fut.setStyleSheet(u"background-color: transparent; border: none;")
        main.setCentralWidget(self.MainWinodw2)
        self.btn_long.raise_()
        self.btn_aggresive.raise_()
        self.btn_defensive.raise_()
        self.btn_bounce.raise_()
        self.spinner_ticker.raise_()
        self.btn_short.raise_()
        self.line.raise_()
        self.label_riskpertrade.raise_()
        self.et_risk.raise_()
        self.label_mtm_label.raise_()
        self.label_MTM.raise_()
        self.btn_execute.raise_()
        self.line_2.raise_()
        self.label_label_spot.raise_()
        self.label_spot.raise_()
        self.label_futures.raise_()
        self.label_label_futures.raise_()
        self.label_future_diff.raise_()
        self.label_label_futures_diff.raise_()
        self.line_3.raise_()
        self.spin_stoploss.raise_()
        self.label_stoploss.raise_()
        self.lv_trades.raise_()
        self.label_trades.raise_()
        self.btn_editrisk.raise_()
        self.btn_trans_label_Fut.raise_()
        self.statusbar = QStatusBar(main)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setStyleSheet(u"color:#F3EF52;")
        main.setStatusBar(self.statusbar)

        self.retranslateUi(main)

        self.btn_aggresive.setDefault(False)
        self.btn_defensive.setDefault(False)
        self.btn_bounce.setDefault(False)
        self.btn_execute.setDefault(False)


        QMetaObject.connectSlotsByName(main)
    # setupUi

    def retranslateUi(self, main):
        main.setWindowTitle(QCoreApplication.translate("main", u"Options Rifle", None))
        self.btn_aggresive.setText(QCoreApplication.translate("main", u"Aggresive", None))
        self.btn_defensive.setText(QCoreApplication.translate("main", u"Defensive", None))
        self.btn_bounce.setText(QCoreApplication.translate("main", u"Bounce", None))
        self.btn_long.setText("")
        self.btn_short.setText("")
        self.label_riskpertrade.setText(QCoreApplication.translate("main", u"Risk Per Trade", None))
        self.label_mtm_label.setText(QCoreApplication.translate("main", u"MTM", None))
        self.label_MTM.setText(QCoreApplication.translate("main", u"+10,900", None))
        self.btn_execute.setText(QCoreApplication.translate("main", u"Execute", None))
        self.label_label_spot.setText(QCoreApplication.translate("main", u"Spot", None))
        self.label_spot.setText(QCoreApplication.translate("main", u"45000", None))
        self.label_futures.setText(QCoreApplication.translate("main", u"45150", None))
        self.label_label_futures.setText(QCoreApplication.translate("main", u"Futures", None))
        self.label_future_diff.setText(QCoreApplication.translate("main", u"150", None))
        self.label_label_futures_diff.setText(QCoreApplication.translate("main", u"Premium DIff.", None))
        self.label_stoploss.setText(QCoreApplication.translate("main", u"Stop loss", None))
        self.label_trades.setText(QCoreApplication.translate("main", u"Trades", None))
        self.btn_editrisk.setText("")
        self.btn_trans_label_Fut.setText("")
    # retranslateUi

